"""api keys idempotency and pagination index

Revision ID: 964a5cd317b6
Revises: b771f8cc7c66
Create Date: 2026-09-26 22:15:53.284714

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "964a5cd317b6"
down_revision: str | None = "b771f8cc7c66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("api_key_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_keys.id"], name=op.f("fk_idempotency_keys_api_key_id_api_keys")
        ),
        sa.PrimaryKeyConstraint("api_key_id", "key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index(
        op.f("ix_idempotency_keys_created_at"), "idempotency_keys", ["created_at"], unique=False
    )
    op.drop_index(op.f("ix_entries_account_id_created_at"), table_name="entries")
    op.create_index(
        "ix_entries_account_id_created_at_id",
        "entries",
        ["account_id", "created_at", "id"],
        unique=False,
    )
    op.add_column("transfers", sa.Column("initiated_by_api_key_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_transfers_initiated_by_api_key_id_api_keys"),
        "transfers",
        "api_keys",
        ["initiated_by_api_key_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transfers_initiated_by_api_key_id_api_keys"), "transfers", type_="foreignkey"
    )
    op.drop_column("transfers", "initiated_by_api_key_id")
    op.drop_index("ix_entries_account_id_created_at_id", table_name="entries")
    op.create_index(
        op.f("ix_entries_account_id_created_at"),
        "entries",
        ["account_id", "created_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_idempotency_keys_created_at"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
