"""create ledger tables

Accounts, transfers and entries, plus two database-level guarantees that
autogenerate cannot detect (so they are written by hand below):

1. Append-only ledger: UPDATE/DELETE on transfers and entries is rejected.
2. Double-entry balance: at COMMIT, every transfer's entries must sum to zero.

Revision ID: b771f8cc7c66
Revises:
Create Date: 2026-09-26 22:04:49.373203

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

APPEND_ONLY_FUNCTION = """
CREATE FUNCTION forbid_ledger_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'ledger table "%" is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$;
"""

# A deferred constraint trigger runs at COMMIT rather than per statement, so a
# transfer can insert its debit and credit rows one at a time; only the final
# state of the transaction must balance.
BALANCED_TRANSFER_FUNCTION = """
CREATE FUNCTION assert_transfer_balanced() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    total BIGINT;
BEGIN
    SELECT SUM(amount) INTO total FROM entries WHERE transfer_id = NEW.transfer_id;
    IF total <> 0 THEN
        RAISE EXCEPTION 'transfer % is unbalanced: entries sum to %', NEW.transfer_id, total
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;
"""


revision: str = "b771f8cc7c66"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("balance", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "allow_negative_balance", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_accounts_currency_iso4217")),
        sa.CheckConstraint(
            "allow_negative_balance OR balance >= 0", name=op.f("ck_accounts_non_negative_balance")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_table(
        "transfers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_transfers_currency_iso4217")),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transfers_positive_amount")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfers")),
    )
    op.create_table(
        "entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transfer_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_entries_non_zero_amount")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_entries_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"], ["transfers.id"], name=op.f("fk_entries_transfer_id_transfers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entries")),
    )
    op.create_index(
        "ix_entries_account_id_created_at", "entries", ["account_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_entries_transfer_id"), "entries", ["transfer_id"], unique=False)
    # ### end Alembic commands ###

    op.execute(APPEND_ONLY_FUNCTION)
    for table in ("transfers", "entries"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_ledger_mutation()"
        )

    op.execute(BALANCED_TRANSFER_FUNCTION)
    op.execute(
        "CREATE CONSTRAINT TRIGGER entries_balanced_per_transfer AFTER INSERT ON entries "
        "DEFERRABLE INITIALLY DEFERRED "
        "FOR EACH ROW EXECUTE FUNCTION assert_transfer_balanced()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER entries_balanced_per_transfer ON entries")
    op.execute("DROP FUNCTION assert_transfer_balanced()")
    for table in ("transfers", "entries"):
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    op.execute("DROP FUNCTION forbid_ledger_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entries_transfer_id"), table_name="entries")
    op.drop_index("ix_entries_account_id_created_at", table_name="entries")
    op.drop_table("entries")
    op.drop_table("transfers")
    op.drop_table("accounts")
    # ### end Alembic commands ###
