"""trace context and scheduled jobs

Revision ID: accbf314f903
Revises: 079b1f12df9a
Create Date: 2026-09-26 22:50:04.017315

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "accbf314f903"
down_revision: str | None = "079b1f12df9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_jobs",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("last_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=16), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_scheduled_jobs")),
    )
    op.add_column("outbox_events", sa.Column("trace_context", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox_events", "trace_context")
    op.drop_table("scheduled_jobs")
    # ### end Alembic commands ###
